version: 0.0
os: windows
files:
  - source: \publish
    destination: C:\ExploringAspNetCore\publish
hooks:
  ApplicationStop:
    - location: .\RemoveApp.ps1
      timeout: 30
  ApplicationStart:
    - location: .\InstallApp.ps1
      timeout: 300
